name: continuous delivery

on:
  push:
    branches:
      - "master"
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "deploy set"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: naufal360/docker-wishlist:v1
      
      - name: update gcp
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          command: |
            sudo docker compose down
            sudo docker image rm naufal360/docker-wishlist:v1
            sudo docker compose up -d